### PR TITLE
Cleaned code with Black & Isort

### PR DESCRIPTION
**Pull request by EliteGreyIT67**

### CODE REVIEW

**Comment by nutzboi** [comment]
this is more appealing to the eye indeed.

**Comment by EliteGreyIT67** [comment]
A trick I learned from working on Tookie-OSINT to keep code easy on the eyes and easy to maintain.

**Comment by nutzboi** [comment]
hm but why do you merge some split lines and split some unified lines? it's better if you stick to one style...
image

**Comment by EliteGreyIT67** [comment]
I prefer to stick with Black code style which I did and it runs smoothly

**Comment by RetrO-M** [comment]
How do you find my tool? Any suggestions for improvement 😊?

**Comment by EliteGreyIT67** [comment]
It popped up multiple times on my substack feed so I decided try running it on Termux and it runs great. Yes there's plenty of room for improvements and I've got some ideas.

**Pull request closed without merging**
